name: "Vulnerability Scan Integration with ASC"

on:
  push:
    branches:
      - develop

jobs:
  vulnerability_scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - run: docker build . -t albertheijn.azurecr.io/sre-vulnerability-scan-test:${{ github.sha }}
        name: docker build
      - uses: Azure/container-scan@v0
        name: scan images for vulnerabilities
        id: container_scan
        continue-on-error: true
        with:
          image-name: albertheijn.azurecr.io/sre-vulnerability-scan-test:${{ github.sha }}
      - uses: azure/login@v1
        with:
          creds: |
            { "clientId": "${{ secrets.AZURE_CLIENT_ID }}", 
            "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
            "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
            "tenantId": "${{ secrets.AZURE_TENANT_ID }}" }
      - run: az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
      - run: az acr login -n albertheijn
      - run: docker push albertheijn.azurecr.io/sre-vulnerability-scan-test:${{ github.sha }}
        name: docker push
      - uses: azure/publish-security-assessments@v0
        name: post logs to app insights
        with:
          scan-results-path: ${{ steps.container_scan.outputs.scan-report-path }}
          connection-string: ${{ secrets.AZ_APPINSIGHTS_CONNECTION_STRING }}
          subscription-token: ${{ secrets.AZ_SUBSCRIPTION_TOKEN }}
